window:
  padding:
    x: 0
    y: 0
font:
  normal:
    family: Iosevka Term SS08
    white:   '#d0d0d0'
  bold:
    family: Iosevka Term SS08
    style: bold
  italic:
    family: Iosevka Term SS08
    style: italic
  size: 8
colors:
  primary:
    foreground: '0xeeeeee'
    background: '0x111111'
