git_protocol: ssh
prompt: enabled
aliases:
  co: pr checkout
  c: repo clone
  f: repo fork
  rc: repo create
  rv: repo view
  re: repo edit
  rm: repo remove
  rn: repo rename
  lr: repo list
  li: issue list
  al: alias
  al-: alias delete
