#!/bin/sh

userresources=$HOME/.config/X11/Xresources
usermodmap=$HOME/.config/X11/Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

if [ -f $sysresources ]; then xrdb -merge $sysresources; fi
if [ -f $sysmodmap ]; then xmodmap $sysmodmap; fi
if [ -f "$userresources" ]; then xrdb -merge "$userresources"; fi
if [ -f "$usermodmap" ]; then xmodmap "$usermodmap"; fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# ______________________________

xset -b            # disable bell
xset r rate 200 30 # adjust typematic delay & rate

xbanish &
dwmblocks &
udiskie &
redshift -t 4500:3000 &

# No compositor
# xsetroot -solid "#0a0a0a"

# With compositor
hsetroot -solid "#0a0a0a"
picom &

# execute dwm in a loop
while true; do
  dwm 2> ~/.dwm.log
done
