#!/usr/bin/env bash

options="Laptop monitor\nDual monitor\nExternal monitor\nOther"

selected=$(echo -e "$options" | dmenu -i)

case "$selected" in
  "Laptop monitor") xrandr --output eDP --primary --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI-A-0 --off;;
  "Dual monitor") xrandr --output eDP --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI-A-0 --primary --mode 3840x2160 --pos 0x0 --rotate normal;;
  "External monitor") xrandr --output eDP --off --output HDMI-A-0 --primary --mode 3840x2160;;
  "Other") arandr;;
esac
