#!/usr/bin/env bash

max_temperature=6500
min_temperature=4500
temperature=$max_temperature
step_size=100

if [ ! -e "/usr/bin/sct" ]; then echo "sct not found"; exit 1; fi

until [ $temperature -eq $min_temperature ]; do
    temperature=$((${temperature}-${step_size}))
    sct "$temperature"
    sleep 0.5
done
