#!/usr/bin/env bash

session="main"

tmux attach-session -t $session || tmux new-session -s $session \; \
  rename-window todo \; \
  send-keys -t 0 "task" C-m \; \
  new-window -n wiki \; \
  send-keys -t 0 "vim $HOME/.wiki/index.md" C-m \; \
  new-window -n music \; \
  send-keys -t 0 "ncspot" C-m \; \
  new-window -n term \; \
  new-window -n make \; \
  split-window -h \; \
  send-keys -t 0 'cd "$HOME/.wiki" && ./entr' C-m \; \
  send-keys -t 1 'cd "$HOME/.wiki" && live-server . --watch *.html' C-m \; \
  select-window -t 2 \;
