#!/usr/bin/env bash

xsetwacom set "Wacom Intuos Pro M Pen stylus" rotate ccw
xsetwacom set "Wacom Intuos Pro M Finger touch" rotate ccw
xsetwacom set "Wacom HID 5214 Pen stylus" rotate ccw
xsetwacom set "Wacom HID 5214 Finger touch" rotate ccw
xsetwacom set "Wacom Intuos Pro M Pen eraser" rotate ccw
xsetwacom set "Wacom Intuos Pro M Pen cursor" rotate ccw
xsetwacom set "Wacom HID 5214 Pen eraser" rotate ccw
xsetwacom set "Wacom Intuos Pro M Pen stylus" rotate ccw

xsetwacom set "Wacom Intuos Pro M Pen stylus" MapToOutput 1080x1920+130+130
xsetwacom set "Wacom Intuos Pro M Finger touch" MapToOutput 1080x1920+130+130
xsetwacom set "Wacom HID 5214 Pen stylus" MapToOutput 1080x1920+130+130
xsetwacom set "Wacom HID 5214 Finger touch" MapToOutput 1080x1920+130+130
xsetwacom set "Wacom Intuos Pro M Pen eraser" MapToOutput 1080x1920+130+130
xsetwacom set "Wacom Intuos Pro M Pen cursor" MapToOutput 1080x1920+130+130
xsetwacom set "Wacom HID 5214 Pen eraser" MapToOutput 1080x1920+130+130
xsetwacom set "Wacom Intuos Pro M Pen stylus" MapToOutput 1080x1920+130+130
