[theme]
background = "#0d0d0d"
primary = "#aaaaaa"
secondary = "#444444"
title = "#aaaaaa"
playing = "#ffffff"
playing_bg = "#0d0d0d"
highlight = "#ffffff"
highlight_bg = "#444444"
error = "#ffffff"
error_bg = "red"
statusbar = "#0d0d0d"
statusbar_progress = "green"
statusbar_bg = "green"
cmdline = "#ffffff"
cmdline_bg = "#0d0d0d"
