notify = true

[theme]
background="black"
primary="#aaa"
secondary="#555"
title="#ccc"
playing="#fff"
playing_selected="#fff"
playing_bg="black"
highlight="#ccc"
highlight_bg="#333"
error="#fff"
error_bg="#111"
statusbar="#ccc"
statusbar_progress="#ccc"
statusbar_bg="black"
cmdline="#ccc"
cmdline_bg="black"
