[theme]
background = "#111111"
primary = "#CCCCCC"
secondary = "#AAAAAA"
title = "#CCCCCC"
playing = "#FFFFFF"
playing_selected = "#FFFFFF"
playing_bg = "#111111"
highlight = "#CCCCCC"
highlight_bg = "#333333"
error = "#FFFFFF"
error_bg = "#111111"
statusbar = "#CCCCCC"
statusbar_progress = "#CCCCCC"
statusbar_bg = "#111111"
cmdline = "#CCCCCC"
cmdline_bg = "#111111"
