[theme]
background = "#1C1C1C"
primary = "#CCCCCC"
secondary = "#AAAAAA"
title = "#CCCCCC"
playing = "#FFFFFF"
playing_selected = "#FFFFFF"
playing_bg = "#1C1C1C"
highlight = "#CCCCCC"
highlight_bg = "#333333"
error = "#FFFFFF"
error_bg = "#1C1C1C"
statusbar = "#CCCCCC"
statusbar_progress = "#CCCCCC"
statusbar_bg = "#1C1C1C"
cmdline = "#CCCCCC"
cmdline_bg = "#1C1C1C"
