[theme]
background = "#000000"
primary = "#aaaaaa"
secondary = "#444444"
title = "#aaaaaa"
playing = "#ffffff"
playing_bg = "#000000"
highlight = "#ffffff"
highlight_bg = "#444444"
error = "#ffffff"
error_bg = "red"
statusbar = "#000000"
statusbar_progress = "green"
statusbar_bg = "green"
cmdline = "#ffffff"
cmdline_bg = "#000000"
