notify = true

[theme]
primary="#aaa"
title="#ccc"
playing="#fff"
playing_selected="#fff"
highlight="#ccc"
highlight_bg="#333"
error="#fff"
error_bg="#333"
statusbar="#ccc"
statusbar_progress="#ccc"
cmdline="#ccc"
# background="black"
# cmdline_bg="black"
# playing_bg="black"
# statusbar_bg="black"
# secondary="#555"
